# humanoid/tests/unit/test_user
from sqlalchemy.exceptions import IntegrityError
from {{package}}.tests import *
from {{package}}.model import meta, User

class TestMyModel(TestModel):
    def test_simpleassert(self):
        """TestMyModel (humanoid): test simple assertion"""
        einstein = User()
        einstein.user_id = 99
        einstein.username = u'einstein'
        einstein.password = "on the other bicycle"
        einstein.password_check = u"on the other bicycle"
        meta.Session.add(einstein)
        meta.Session.commit()
        ind1 = meta.Session.query(User).filter_by(username = u'einstein').one()
        assert ind1 == einstein
    
    
    def test_exception(self):
        """TestMyModel (humanoid): test Integrity Exception"""
        me = User()
        me.username = u'giuseppe'
        meta.Session.add(me)
        me_again = User()
        me_again.username = u'giuseppe'
        meta.Session.add(me_again)
        self.assertRaises(IntegrityError, meta.Session.commit)
        meta.Session.rollback()
    

# --- Overwritten by shabti_humanoid template


